### ISSUE TITLE
Uncaught (in promise) DOMException: IDBDatabase.transaction: 'meta' is not a known object store name

### ISSUE THREAD

**Issue by mueslie** [zacharygriffee/random-access-idb#4]
Hi, 
thank you for your effort updating the random-access-idb library. I finally got Hyperbee running in the browser persisting data 👍 

I face an issue when I try to run my app in firefox: 
On first call:
![grafik](https://github.com/zacharygriffee/random-access-idb/assets/7595311/6ad5d41e-9529-4466-a1c9-c417041cb905)

On subsequent calls:
![grafik](https://github.com/zacharygriffee/random-access-idb/assets/7595311/4b5cda5d-388c-4fef-ab92-b89d3ce6fa47)

Running it in a Chromium based browser it works.
```

import Hyperbee from 'hyperbee';
import Corestore from 'hypercore'

import defaultMaker from "./../assets/rai.min.js"; // <= Version 3.1.2
export async function initHDB(){

    const core = new Corestore( (file) => defaultMaker(file, {directory: "/local/"}) )
    const db = new Hyperbee(core, {keyEncoding: 'utf-8', valueEncoding: 'json'})

    return db;   
}
```

If you need more information please let me know :) 

Best regards

**Comment by mueslie** [comment]
I changed the import to the index.js instead of index.min.js and now it works also in firefox. 

Error 70

**Comment by zacharygriffee** [comment]
Apologies, been rather busy lately. I will definitely look into why the bundle isn't working.

**Comment by zacharygriffee** [comment]
Bundle should be working on update I'm pushing in few moments.
